name: pr

on:
  pull_request_target:

permissions:
  contents: read

concurrency:
  group: pr-${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      targetSha: ${{ github.event.pull_request.head.sha }}
  test:
    uses: ./.github/workflows/test.yml
    with:
      targetSha: ${{ github.event.pull_request.head.sha }}
  unlock:
    if: github.event_name != 'pull_request' && always()
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    permissions:
      statuses: write
    steps:
      - name: set required status check
        uses: actions/github-script@v8.0.0
        env:
          RESULTS: ${{ toJSON(needs.*.result) }}
        with:
          script: |
            const { serverUrl, repo, runId, payload } = context
            const target_url = `${serverUrl}/${repo.owner}/${repo.repo}/actions/runs/${runId}?pr=${payload.pull_request.number}`
            await github.rest.repos.createCommitStatus({
              ...repo,
              sha: payload.pull_request.head.sha,
              context: 'no PR failures',
              state: JSON.parse(process.env.RESULTS).every(status => status == 'success') ? 'success' : 'error',
              target_url,
            })

